name: JewelsGens
version: ${project.version}
main: org.minejewels.jewelsgens.JewelsGens
api-version: 1.19
depend: [ AbyssLib, DecentHolograms, Vault ]
authors: [ Consciences ]
description: Custom generator plugin!
