name: JewelsGens
version: 1.0.0
main: org.minejewels.jewelsgens.JewelsGens
api-version: 1.19
depend: [ AbyssLib, DecentHolograms, Vault ]
softdepend: [ JewelsRealms ]
authors: [ Consciences ]
description: Custom generator plugin!
